### ISSUE TITLE
Recovery setup: deploy Recovery master copy and integrate with AddUser

### ISSUE THREAD

**Issue by abhayks1** [OpenSTFoundation/openst.js#43]
Below are the steps:
- Deploy Delayed Recovery MasterCopy  in UserSetup: lib/setup/User.js.
- Deploy proxy for "Delayed Recovery contract". The method can go to lib/helper/User.js.
- Integrate Recovery module with createUserWallet  method. Below how the current createUserWallet looks like:
```
 createUserWallet(
    owners,
    threshold,
    to,
    data,
    sessionKeys,
    sessionKeysSpendingLimits,
    sessionKeysExpirationHeights,
    txOptions
  )
``` 
   **to**, **data** argument of createUserWallet needs to integrate with delayed Recovery module.

**Comment by benjaminbollen** [comment]
LGTM, it's a big ticket, so some additional notes:
> * Deploy Delayed Recovery MasterCopy  in UserSetup: lib/setup/User.js.
we additionally need Gnosis' `CreateAndAddModules.sol` to be deployed, so a complete list of deployments in `UserSetup` (please correct) is:
- UserWalletFactory (done)
- GnosisSafe as MasterCopy (done)
- TokenHolder as MasterCopy (done)
- DelayedRecovery as MasterCopy
- CreateAndAddModules, a helper contract

**Comment by benjaminbollen** [comment]
> * Deploy proxy for "Delayed Recovery contract". The method can go to lib/helper/User.js
this is done by the helper contract `CreateAndAddModules`, so it does not need to be explicitly deployed.  Rather the address of the master copy of `DelayedRecovery` will be passed in in `data` of `createUserWallet` / GnosisSafe.setup()

Wrt the parameters `to` and `data`, it is my understanding (but this probably needs scrutiny) that:
- `to` is the address of the `CreateAndAddModules` helper contract
- `data` = `<lenPrefix><A>`

where `A` = abi.encodeWithFuncSelector("createProxy", addressMCDelayedRecoveryModule, B)
and `B`=abi.encodeWithFuncSelector("setup", <paramsDelayedRecoverySetup>)

**Comment by benjaminbollen** [comment]
so these can be taken together in one PR or made into separate tickets&PRs
